version: '3.3'

services:
  frontend:
    container_name: webapp
    build: ./frontend
    #build: ./f
    restart: always
    depends_on:
      - balancer
    ports:
      - "80:80"
      #- "3000"
    networks:
      - frontend_network
      - service_network
    environment:
    - apiURL=balancer

  backend1:
    container_name: api1
    build: ./backend
    restart: always
    ports:
      #- "3000:3000"
      - "3000"
    networks:
      - service_network
      - db_network
    volumes:
      - /proc:/usr/src/app/lecturas
    environment:
    - IP_DB=database
    - SERVER_NAME=201700543

  backend2:
    container_name: api2
    build: ./backend
    restart: always
    ports:
      #- "3000:3000"
      - "3000"
    networks:
      - service_network
      - db_network
    volumes:
      - /proc:/usr/src/app/lecturas
    environment:
    - IP_DB=database
    - SERVER_NAME=2017

  balancer:
    container_name: apibalancer
    image: nginx #:latest
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    ports:
      - "4000:4000"
    networks:
      - service_network      
      #service_network:
          #ipv4_address: 172.35.75.2

  database:
    container_name: db
    build: ./database
    restart: always
    environment:
      #MYSQL_DATABASE: "ayd2"
      #MYSQL_USER: "root"
      #MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - "3307:3306"
    #expose:
    #  - "3306"
    volumes:
      - ./database/copia:/var/lib/mysql
    #logging:
    #  driver: none
    networks:
      - db_network

networks:
  frontend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1
  
  service_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.35.75.0/24
          gateway: 172.35.75.1

  db_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.15.0/24
          gateway: 10.10.15.1